language: python


python:
    - "2.7"

sudo: required

services:
    - docker

notifications:
  email:
    recipients:
      - arfathpasha@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

branches:
  only:
    - master
    - staging
    - develop

before_install:
    - docker version
    - javac -version
    - java -version

install:
    - git clone https://github.com/kbase/jars
    - git clone https://github.com/kbase/kb_sdk
    - cd kb_sdk
    - make
    - make sdkbase
    - docker images
    - export PATH=$(pwd)/bin:$PATH
    - cd ../
    - git clone https://github.com/sjyoo/coexpression
    - cd coexpression
    - mkdir test
    # run the kb-sdk test command once to build missing module files and dirs
    - kb-sdk test -s
    # add test config
    env:
        - TEST_USER=kbasetest
        - TEST_PASSWORD=@Suite525
    - sed -i "s/test_user=/test_user=$TEST_USER/" test_local/test.cfg
    - sed -i "s/test_password=/test_password=$TEST_PASSWORD/" test_local/test.cfg
    - sed -i 's\https://appdev.kbase.us/services\https://ci.kbase.us/services\' test_local/test.cfg
    # temporary fix for host::container user mapping (until it is fixed in kb-sdk)
    - sed -i 's/$(id -u)/0:0/' test_local/run_tests.sh

script:
    - kb-sdk test -s