language: python

python:
    - "2.7"

sudo: required

services:
    - docker

before_install:
    - docker version
    - javac -version
    - java -version

install:
    - git clone https://github.com/kbase/jars
    - git clone https://github.com/kbase/kb_sdk
    - cd kb_sdk
    - make
    - make sdkbase
    - docker images
    - export PATH=$(pwd)/bin:$PATH
    - cd ../
    - git clone https://github.com/arfathpasha/coexpression
    - cd coexpression
    - mkdir test
    # run the kb-sdk test command once to build missing module files and dirs
    - kb-sdk test -s
    # add test config
    - sed -i 's/test_user=/test_user=kbasetest/' test_local/test.cfg
    - sed -i 's/test_password=/test_password=@Suite525/' test_local/test.cfg
    - sed -i 's\https://appdev.kbase.us/services\https://ci.kbase.us/services\' test_local/test.cfg
    # temporary fix for host to container user mapping
    - sed -i 's/$(id -u)/0:0/' test_local/run_tests.sh

script:
    - kb-sdk test -s